site_name: VoltScript Collections
site_url: https://github.com/HCL-TECH-SOFTWARE/voltscript-collections/
site_description: >-
  VoltScript Collections: Collection and Map classes for VoltScript
use_directory_urls: false
# Theme Configuration
theme:
  name: material
  logo: assets/images/VoltMXGoLogo.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
  font: false
  #  text: Roboto
  #  code: Roboto Mono
  favicon: assets/images/favicon.png
#  palette:
#    - scheme: default
#      primary: indigo
#      accent: indigo
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
#    - scheme: slate
#      primary: indigo
#      accent: indigo
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode

  # Static files
  static_templates:
    - 404.html

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - abbr
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/includes/glossary.md
  - pymdownx.superfences
  - toc:
     title: On this page

# Copyright
copyright: >-
  Copyright &copy; 2023-2025, HCL America, Inc. | <a href="https://www.hcl-software.com/legal/privacy" target="_blank">Privacy Statement</a> | <a href="https://www.hcl-software.com/legal/terms-use" target="_blank">Terms of Use</a> <br/>
  <a href="#__consent">Change cookie settings</a>
#  Copyright &copy; 2022-23, HCL America, Inc. -
#  <a href="#__consent">Change cookie settings</a>
extra:
  productversion: 1.0.6
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HCL-TECH-SOFTWARE
  analytics:
    provider: google
    property: UA-169645537-2
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

# Repository
repo_url: https://github.com/HCL-TECH-SOFTWARE/voltscript-collections/
repo_name: HCL-TECH_SOFTWARE/voltscript-collections
edit_uri: ""

# Customization
extra_css:
  - assets/css/style.css
  - assets/css/style1.css

watch:
  - docs/includes/glossary.md

plugins:
  - awesome-pages
  - search
  - tags
  # disabled unti we get rid of reletove URL - markdownextradata
  #- mike:
  #    canonical_version: latest
  #- git-revision-date-localized:
  #    type: date